### ISSUE TITLE
How to generate the input files and view the output results.

### ISSUE THREAD

**Issue by xuhenry** [HydroComplexity/GCSFlow#2]
Dear authors,
    I  just learning the code GCSFlow, but there is no document on how to use  the code.
    Where can I find the documents on how to use it ? for example, how to prepare the input files and how to show the results?  
   I try to open the results with Paraview, but there are some errors.
   Can you help me?
Thanks a lot!
Henry

**Comment by levuvietphong** [comment]
Hi Heny,

I have uploaded scripts to prepare inputs data for GCSFlow, so you can prepare input data for yourself to run the model:
1. You can use either MATLAB or python to create forcing, topography and other inputs. The input files are stored in NetCDF format.
2. The outputs of GCSFlow are in netCDF format as well. You can use any languages/software to view and process the results.
3. If you see blank results, it is very likely the model didn't read the NetCDF input data properly, and it produces all NaN or 0 values. Some computers show this issue. Creating the inputs again with python script may help to fix this issue.
4. GCS-Flow is not maintained in our group. We have merged it into Dhara modeling system (https://github.com/HydroComplexity/Dhara). We recommend you to use documents & tutorial in Dhara for processing the results. A key difference is that GCSFlow use ADI scheme, whereas Dhara use fully implicit finite difference scheme.

Thanks.

**Comment by xuhenry** [comment]
Dear Le,
   Many thanks for your reply. Is  the Dhara can be used for the coupling of surface flow and sub-surface flow? 
Thanks a lot!
Best regards,
Henry

**Comment by HydroComplexity** [comment]
Yes --

_____
Praveen Kumar

**Comment by levuvietphong** [comment]
Yes, Dhara includes the coupled surface-subsurface flow modeling. It also incorporates a multi-layer canopy model to simulate land-atmosphere interaction above the surface (optional module). You can also simulate nutrient dynamics & some other processes with Dhara.

**Comment by xuhenry** [comment]
Dear Le, 
   Thanks a lot! Very good! I'll try it.
Best regards,
Henry
